# Generated by Django 5.2.6 on 2025-10-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salud', '0002_departamento_remove_entidad_regimen_entidad_and_more'),
        ('usuarios', '0006_usuario_fecha_nacimiento_beneficiario_delete_novedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_afiliacion', models.DateField(auto_now_add=True)),
                ('empleador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salud.empleador')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.eps')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.regimen')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_novedad', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=50)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('tipo_solicitud', models.CharField(choices=[('Afiliacion', 'Afiliacion'), ('Cambio de EPS', 'Cambio de EPS'), ('Actualizacion de Datos', 'Actualizacion de Datos')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='solicitudes/')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliaciones.solicitud')),
            ],
        ),
    ]
