# Generated by Django 5.2.6 on 2025-11-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='archivosolicitud',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
