# Generated by Django 5.2.6 on 2025-11-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliaciones', '0002_afiliacion_estado_archivosolicitud_name'),
        ('salud', '0002_departamento_remove_entidad_regimen_entidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliacion',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salud.municipio'),
        ),
        migrations.AlterField(
            model_name='afiliacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('EN TRAMITE', 'EN TRAMITE'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.CharField(choices=[('Cambio de EPS', 'Cambio de EPS'), ('Actualizacion de Datos', 'Actualizacion de Datos')], max_length=50),
        ),
    ]
