# Generated by Django 5.2.6 on 2025-10-11 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_delete_empleador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa_Aportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad_Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Publica', 'Publica'), ('Privada', 'Privada'), ('Mixta', 'Mixta')], max_length=50)),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_dane', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regimen', models.CharField(choices=[('Contributivo', 'Contributivo'), ('Subsidiado', 'Subsidiado')], max_length=50)),
                ('fuente_cotizacion', models.CharField(max_length=100)),
                ('porcentaje_cotizacion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria'), ('PP', 'Pasaporte')], max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa_aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.empresa_aportante')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad_Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.entidad_salud')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.regimen')),
            ],
        ),
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_afiliacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('Empleador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salud.empleador')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.eps')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.regimen')),
            ],
        ),
        migrations.CreateModel(
            name='SedeEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.eps')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.municipio')),
            ],
        ),
    ]
