# Generated by Django 5.2.6 on 2025-10-13 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_dane', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entidad_regimen',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='entidad_regimen',
            name='regimen',
        ),
        migrations.RemoveField(
            model_name='empresa_aportante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresa_aportante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa_aportante',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='empresa_aportante',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empleador',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='sedeeps',
            name='horario_atencion',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdministradorEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria'), ('PP', 'Pasaporte')], max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(default='2000-01-01')),
                ('eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salud.eps')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salud.departamento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SedeEmpresaAprotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('municipio', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.empresa_aportante')),
            ],
        ),
        migrations.DeleteModel(
            name='Afiliacion',
        ),
        migrations.DeleteModel(
            name='Entidad_Salud',
        ),
        migrations.DeleteModel(
            name='Entidad_Regimen',
        ),
    ]
