# Generated by Django 5.2.6 on 2025-10-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleador',
        ),
    ]
