# Generated by Django 5.2.6 on 2025-11-04 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_fecha_nacimiento_beneficiario_delete_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='beneficiario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
